### ISSUE TITLE
the U-Boot does not outpt boot message

### ISSUE THREAD

**Issue by Chongba-w** [joholl/rpi4-uboot-tpm#11]
Hello, 
I have a try on the rpi3B+ according to your repo. The kernel finally is loaded successfully and the file _tpm0_ occers in the _/dev_.
But when booting, the serial terminal does not receive the message of U-Boot as the U-Boot does not exist. Instead, I was told to login directly. So, how to enter the U-Boot console?

**Comment by Chongba-w** [comment]
Sorry，I konw the problem.

**Comment by parthghughri** [comment]
Hello @Chongba-w,
It will be really helpful if you can explain a bit about the issue that you faced, and how did you connect the TPM and UART simultaneously with RPI4?

Thank you.

**Comment by Chongba-w** [comment]
Hello，Parth.
Thanks for your replying. I have solved the problem. Wish you a good day!

**Comment by parthghughri** [comment]
Thanks @Chongba-w can you help me with the connections to make with TPM, RPI4 & UART that allow us to access TPM in u-boot shell. or what connection did you make?
