### ISSUE TITLE
LPC tpm cycle 

### ISSUE THREAD

**Issue by lostzam** [joholl/rpi4-uboot-tpm#17]
Hi.
I dont know if is there a true place to ask this question or not. my apologies.
Can i speak to you about tpm cycle sequences over email?
Can i have your email address?

**Comment by lostzam** [comment]
Is there anyone who can help me with LPC TPM cycles?

**Comment by joholl** [comment]
I'm sorry but I do not have the time to provide support, here.

This is off-topic, so I'm going to close this.
