### ISSUE TITLE
Is compatible with tpm2-tss

### ISSUE THREAD

**Issue by AbelAguilarF** [joholl/rpi4-uboot-tpm#19]
can you write dtoverlay=tpm-slb9670 instead of dtoverlay=tpm-soft-spi? for me didn't work.

**Comment by joholl** [comment]
Your title does not fit the question.

> Is compatible with tpm2-tss

You cannot use tpm2-tss with mainline U-Boot. After booting into a Linux system, you can use the `tpm2-tss` there, yes.

> Can you write dtoverlay=tpm-slb9670 instead of dtoverlay=tpm-soft-spi? for me didn't work.

No you cant. `tpm-soft-spi` is an arbitrary name I chose for my custom device tree overlay. `tpm-slb9670` is the standard one, but it only works with Linux (which has drivers with hardware support for SPI on the RPi), not with U-Boot. U-Boot does not have such a driver, so we need to use soft-spi. Therefore we need a custom device tree overlay.
