### ISSUE TITLE
tpm_tis_spi_valid_status always returning ff as status this causesTPM commands to not work

### ISSUE THREAD

**Issue by svundru** [joholl/rpi4-uboot-tpm#2]
I followed the instructions form this repository with rpi 4/uboot latest/infineon TPM2. That worked for me and able to make TPM command work.

I replaced the infineon TPM2 with STMicro TPM2. It was able to detect the TPM2 device and probe it with soft SPI. get locality that goes as part of probing works for me and display the TPM specific information like  vid, did and rid. 

However the startup command is not working.  I see tpm_tis_spi_valid_status always gives the status values as FF for STMicro TPM2. I see this values as 0x88 and 0x80 for Infineon.

Can you please provide some suggestion to debug this issue? Lee me know if you need more information.

**Comment by svundru** [comment]
what does it takes to make these instructions work on Raspberry pi model 3 with infenion TPM2?

**Comment by joholl** [comment]
I'm glad to hear that you could make the Infineon TPM2 work with the latest u-boot.

You probably already made sure that your STM TPM is not broken. This sounds like a driver issue with the TIS protocol (maybe related to soft-spi?). To be honest, I'm not a TIS expert, but I think I recall having had problems with TIS wait states with non-Infineon TPMs before. I'm sorry for not being able to help you more than just pointing to the [TIS spec](https://trustedcomputinggroup.org/wp-content/uploads/TCG_PCClientTPMInterfaceSpecification_TIS__1-3_27_03212013.pdf).

Keep me updated in case you find the solution!

**Comment by svundru** [comment]
Thanks for the response. I forgot to update this issue, I was able to resolve the issue. I was using a socketed board to mount the TPM with ST. I had to change chip select on that board. I didn't have to change driver. Seems like driver is working as expected. Thanks for all your support. You can close this issue.

**Comment by joholl** [comment]
Thanks for the update!
