### ISSUE TITLE
How to add the crypto APIs of tpm in u-boot?

### ISSUE THREAD

**Issue by saravanj24** [joholl/rpi4-uboot-tpm#20]
Hi,
We are planning to create keys and encrypt/decrypt the files from u-boot using TPM.
Could you please point us to references for  include the crypto APIs? or where need to start with?

Your help is much appreciated.

Thanks,
saravanan

**Comment by joholl** [comment]
Sorry, I do not have the time to support such questions.

All I can say is that [here](https://source.denx.de/u-boot/u-boot/-/blob/master/cmd/tpm-v2.c#L386) you can find the TPM commands supported by the U-Boot shell. I'm not familiar with if/how U-Boot supports any form of file/fs encryption.
