### ISSUE TITLE
Couldn't set TPM 0 (rc = 1) error

### ISSUE THREAD

**Issue by lap1nou** [joholl/rpi4-uboot-tpm#4]
Hello,

I followed all the steps and once I'm in the U-boot shell I got this error after typing `tpm2 init`:
```
Couldn't set TPM 0 (rc = 1)
```

I got a Raspberry 3B+ and an Infineon Optigal SLM9760 TPM, I tried your device tree and this device tree:
https://www.infineon.com/dgdl/Infineon-App-Note-SLx9670-TPM2.0_Embedded_RPi_DI_SLx-ApplicationNotes-v01_03-EN.pdf?fileId=5546d46267c74c9a01684b96e69f5d7b

I used the last U-boot version (from their Github repo) and I was able to use the TPM2 on another Linux Kernel 32 bit (Raspian) and now I installed another kernel 64 bit (Ubuntu Server).

Have you any idea why this isn't working ?

**Comment by joholl** [comment]
Sorry for the late answer. The linux kernel (basically anything on your root partition) should not have an impact on the behavior of the TPM in u-boot, because u-boot lives on your boot partition. Did you change anything else?

If you solved this problem already, please let us know about the solution :)

**Comment by lap1nou** [comment]
Hello,

> Sorry for the late answer.

No problem.

> The linux kernel (basically anything on your root partition) should not have an impact on the behavior of the TPM in u-boot, because u-boot lives on your boot partition. Did you change anything else?

I tried to adapt every command to an RPI3, I don't remember all the commands I used.

> If you solved this problem already, please let us know about the solution :)

I solved it by switching over to an RPI4 and it worked like a charm.

I really don't know why this hasn't worked on an RPI3, I would recommend anyone with the same problem to simply switch to an RPI4.

I guess we can close this issue.

**Comment by parthghughri** [comment]
Hello @lap1nou 
Can you explain a bit about how you connected TPM and UART simultaneously with RPI4? It will be really helpful, thank you.
