### ISSUE TITLE
How to set the PCR's in u-boot

### ISSUE THREAD

**Issue by Zetanova** [joholl/rpi4-uboot-tpm#5]
Is there a recommended way to generate some hashes of kernel file, hardware id's like CPU serial number 
and set some PCR's in u-boot?

Get some serial numbers:
https://github.com/AndrewFromMelbourne/raspi_serialnumber

**Comment by joholl** [comment]
Sure, you can load the kernel from the SD card into memory, use the [hash](https://source.denx.de/u-boot/u-boot/-/blob/master/cmd/hash.c#L46) command on the memory area and then use the [tpm2 pcr_extend](https://source.denx.de/u-boot/u-boot/-/blob/master/cmd/tpm-v2.c#L408) command.

**Comment by Zetanova** [comment]
that was not the question

raspberry has view hardware ID like CPU serial number 
but would need a driver or something for it to read it out from uboot

**Comment by joholl** [comment]
This is an issue tracker for this repository. Please ask your question elsewhere, e.g. in an appropriate forum or a stackexchange site.
