### ISSUE TITLE
How to verify u-boot

### ISSUE THREAD

**Issue by hcjjmt** [joholl/rpi4-uboot-tpm#9]
I want to know how to use TPM to verify that u-boot is trusted on raspberry pie. I don't know who should verify the credibility of u-boot. Could you help me?

**Comment by joholl** [comment]
As far as I know, it is not possible to verify u-boot before booting into it, that is by the Raspberry Pi bootloader. See the manual:

https://github.com/joholl/rpi4-uboot-tpm/blob/8fbd6877af794d832f25e4d6307cfd6501fa160d/README.md?plain=1#L10-L20

**Comment by Zetanova** [comment]
I had the same question and would like to verify the hardware ID's 
especially over the CPU Id

https://github.com/joholl/rpi4-uboot-tpm/issues/
